### ISSUE TITLE
AttributeError: 'MjModel' object has no attribute 'flex_xvert0'

### ISSUE THREAD

**Issue by XilunZhangRobo** [WEIRDLabUW/asid#4]
Hi Authors, 
Thanks for the amazing work! 
I am trying to reproducing your results by running train.py with default configs.
I am running into an error as follows:
Traceback (most recent call last):
  File "/home/xilun/ENTER/envs/asid/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/xilun/ENTER/envs/asid/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xilun/asid/env/wrappers/vec_wrapper.py", line 13, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/xilun/asid/env/wrappers/asid_vec.py", line 22, in make_env
    env = RobotEnv(**robot_cfg_dict, device_id=device_id)
  File "/home/xilun/asid/env/robot/robot_env.py", line 150, in __init__
    self._robot = MujocoManipulatorEnv(
  File "/home/xilun/asid/env/robot/franka_mujoco.py", line 45, in __init__
    super().__init__(
  File "/home/xilun/asid/env/robot/franka_base.py", line 29, in __init__
    self.launch_ik()
  File "/home/xilun/asid/env/robot/franka_base.py", line 32, in launch_ik
    self._ik_solver = RobotIKSolver(
  File "/home/xilun/asid/env/robot/inverse_kinematics/robot_ik_solver.py", line 21, in __init__
    self._physics = mjcf.Physics.from_mjcf_model(self._arm.mjcf_model)
  File "/home/xilun/ENTER/envs/asid/lib/python3.9/site-packages/dm_control/mjcf/physics.py", line 461, in from_mjcf_model
    return cls.from_xml_string(xml_string=xml_string, assets=assets)
  File "/home/xilun/ENTER/envs/asid/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 443, in from_xml_string
    return cls.from_model(model)
  File "/home/xilun/ENTER/envs/asid/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 426, in from_model
    return cls(data)
  File "/home/xilun/ENTER/envs/asid/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 123, in __init__
    self._reload_from_data(data)
  File "/home/xilun/ENTER/envs/asid/lib/python3.9/site-packages/dm_control/mjcf/physics.py", line 496, in _reload_from_data
    super()._reload_from_data(data)
  File "/home/xilun/ENTER/envs/asid/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 407, in _reload_from_data
    model=index.struct_indexer(self.model, 'mjmodel', axis_indexers),
  File "/home/xilun/ENTER/envs/asid/lib/python3.9/site-packages/dm_control/mujoco/index.py", line 628, in struct_indexer
    attr = getattr(struct, field_name)
AttributeError: 'MjModel' object has no attribute 'flex_xvert0'

Do you have any insights on how to solve the issue? Thanks!

**Comment by franzele21** [comment]
I had the same problem (for something else [TD-MPC2]), and upgrading `dm-control` to the latest version (1.0.30 at the time I write this) fixed it.

**Comment by sai-prasanna** [comment]
@XilunZhangRobo  Did you manage to fix this?
